name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Using your EC2 as a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure Docker is Running
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Add User to Docker Group (if needed)
        run: |
          sudo usermod -aG docker $(whoami)
          newgrp docker

      - name: Enable BuildKit and Build Docker Image
        run: |
          export DOCKER_BUILDKIT=1
          sudo docker build -t my-html-app .

      - name: Stop and Remove Old Container
        run: |
          sudo docker stop my-html-container || true
          sudo docker rm my-html-container || true

      - name: Run New Container
        run: sudo docker run -d -p 80:80 --name my-html-container my-html-app
